fos_rest:
    body_converter:
        enabled: true
    view:
        formats:
            json: true
            rss: false
            xml: false 
        view_response_listener: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    param_fetcher_listener: true
